version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
    ports:
      - "8090:8080"
    networks:
      - ms-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/realms/master" ]
      interval: 10s
      timeout: 5s
      retries: 10



  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ms-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  eurekaserver:
    build: ./eurekaserver
    container_name: eurekaserverr
    networks:
      - ms-network
    healthcheck:
      test: "curl --fail --silent http://localhost:8761/actuator/health | grep UP || exit 1"
      interval: 10s

  configserver:
    build: ./configserver
    container_name: configserverr
    networks:
      - ms-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8761/eureka/
    healthcheck:
      test: "curl --fail --silent http://localhost:9999/actuator/health | grep UP || exit 1"
      interval: 10s
    depends_on:
      eurekaserver:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  gateway:
    build: ./gatewayserver
    container_name: gatewayy
    ports:
      - "8888:8888"
    networks:
      - ms-network
    environment:
      - DISCOVERY_SERVICE_URL=http://eurekaserver:8761/eureka
      - CONFIG_SERVICE_URL=http://configserver:9999
      - KEYCLOAK_URL=${KEYCLOAK_URL:-http://host.docker.internal:8090}
    healthcheck:
      test: "curl --fail --silent http://localhost:8888/actuator/health | grep UP || exit 1"
      interval: 10s
    depends_on:
      eurekaserver:
        condition: service_healthy
      keycloak:
        condition: service_healthy
      configserver:
        condition: service_healthy

  sections_ms:
    build: ./section-microservice
    container_name: section_ms
    networks:
      - ms-network
    environment:
      - DISCOVERY_SERVICE_URL=http://eurekaserver:8761/eureka
      - CONFIG_SERVICE_URL=http://configserver:9999
    healthcheck:
      test: "curl --fail --silent http://localhost:8080/actuator/health | grep UP || exit 1"
      interval: 10s
    depends_on:
      eurekaserver:
        condition: service_healthy
      configserver:
        condition: service_healthy

  students_ms:
    build: ./student-microservice
    container_name: student_ms
    networks:
      - ms-network
    environment:
      - DISCOVERY_SERVICE_URL=http://eurekaserver:8761/eureka
      - CONFIG_SERVICE_URL=http://configserver:9999
    healthcheck:
      test: "curl --fail --silent http://localhost:8081/actuator/health | grep UP || exit 1"
      interval: 10s
    depends_on:
      eurekaserver:
        condition: service_healthy
      configserver:
        condition: service_healthy
      sections_ms:
        condition: service_healthy


networks:
  ms-network:
    driver: bridge
